In [5]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Height': [170, 175, 183],
    'City': ['New York', 'San Francisco', 'Los Angeles']
}
df = pd.DataFrame(data)

# Display summary statistics
df_stats = df.describe()
print(df_stats)

        Age      Height
count   3.0    3.000000
mean   30.0  176.000000
std     5.0    6.557439
min    25.0  170.000000
25%    27.5  172.500000
50%    30.0  175.000000
75%    32.5  179.000000
max    35.0  183.000000